### ISSUE TITLE
Black screen and crash

### ISSUE THREAD

**Issue by EmilMoe** [manolz1/cities2-gptk-fix#1]
After following your steps, when I open the game the screen stays black for 20 seconds and then quits.

I installed Whiskey, installed dotnet48, copied system32 version.dll til version_orig.dll and your dll into the Skylines folder in steamapps.

**Comment by manolz1** [comment]
Hi @EmilMoe , can you provide more details?

1. Which Mac are you trying to run it on (specs and OS version)?
2. What are your whisky settings? Are you using msync/esync? (try toggling these to see if it makes any difference)
3. Which version of the game are you trying it on?
4. Does it happen on the launcher or when the game is trying to start?
5. Do you get a unity or wine crash message?

Also, can you try with crossover as well?

**Comment by zrll12** [comment]
Crashed on my machine as well.
macOS 14.2.1
whisky MSync, DXVK not enabled, Retina not enabled, Windows10 18362
game version 1.0.18f1
crossover tried but not success
The game quit before anything showed up on the screen.
1.0.11f1 was able to play, and 1.0.12f1 will stuck on the loading screen(with circles) on startup

**Comment by manolz1** [comment]
@zrll12 do you have any wine or unity crashlog?

I don't have access to cities skylines 2 at the moment, I will try to get access to the game again and investigate. In the meantime can you try delete this file and see if it will work for you:

 Cities2_Data/Plugins/x86_64/lib_burst_generated.dll

**Comment by zrll12** [comment]
@manolz1 After deleting the file, the game is stuck before anything shows up, the cursor has changed.
[logs.zip](https://github.com/manolz1/cities2-gptk-fix/files/13792004/logs.zip)

**Comment by chickenwaddle77** [comment]
_Download the latest release from this repo and copy version.dll into the same folder as Cities2.exe in your bottle_

Does this mean I still copy the version.dll from system32 or is there a version.dll within the repo folder?

**Comment by manolz1** [comment]
@zrll12 was there any wine crash logs as well? Is your Macbook Apple silicon/what model is it? Also just to confirm, you're trying with gptk 1.1?

@chickenwaddle77 

Step 1)
Copy version.dll from the system32 folder in your bottle into the same folder as cities2.exe, then rename it to version_orig.dll. 

Step 2) 
Download the latest release of the fix
https://github.com/manolz1/cities2-gptk-fix/releases/latest

Step 3) 
Inside the release there is a version.dll, copy this alongside version_orig.dll from step 1

**Comment by zrll12** [comment]
I'm using MacBook Pro 16 inch with M2 Max.
The version of crossover is 23.7.1.
How can I get logs and gptk versions using crossover?

**Comment by zrll12** [comment]
Update: was able to run game 1.0.18f1(3860.252277) [5303.31514] with whisky 2.2.2 and dll not patched.
I guess whisky updated gptk automatically but I don't know how to confirm the gptk version so I have no evidence on it.
But with an extremely low fps(for the same save, previous 30fps, but current 5fps).

**Comment by EmilMoe** [comment]
Hi, thanks for keeping the thread alive, I was off due Christmas.

Still have all the same issues though. The launcher wants to "re"-install and then crashes.

It's a MacBook Air M2.

```
Whisky Version: 2.2.2
Date: 2024-01-03T07:37:06Z
macOS Version: 14.2.1

Bottle Name: Windows 10
Bottle URL: /Users/emil/Documents/Whiskey/A40E48A0-AB93-41FB-9E90-74CD04B7EC2E

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/emil/Documents/Whiskey/A40E48A0-AB93-41FB-9E90-74CD04B7EC2E/drive_c/Program Files (x86)/Steam/steamapps/common/Cities Skylines II/Cities2.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/emil/Documents/Whiskey/A40E48A0-AB93-41FB-9E90-74CD04B7EC2E";
}

msync: bootstrapped mach port on wine-2ec91fb-msync.
msync: up and running.
0358: thread_get_state failed on Apple Silicon - faking zero debug registers
037c: thread_get_state failed on Apple Silicon - faking zero debug registers
rface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
03ec: thread_get_state failed on Apple Silicon - faking zero debug registers
0404: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] Created VkInstance for Vulkan version 1.0.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
03f0:err:wininet:HTTP_ParseRfc850Date unexpected month format L" Dec 2023 21:11:00 UTC"
01f4: thread_get_state failed on Apple Silicon - faking zero debug registers
03f0:err:wininet:HTTP_ParseDate unexpected date format L"Sun, 31 Dec 2023 21:11:00 UTC"
```

**Comment by EmilMoe** [comment]
I can see the Paradox Interactive folder in Program Files is empty. That might be 1 clear error?

**Comment by EmilMoe** [comment]
I got it working now, switched to ESync and skipped Paradox Launcher https://steamcommunity.com/sharedfiles/filedetails/?id=3059994428

Also ran dotnot48 and win10 in Whiskey

**Comment by EmilMoe** [comment]
It's running about 20 FPS on low settings in a new game on my MacBook Air 2. Tabbing out of the game makes it stuck when coming back.

Hopefully they fix the performance.

Btw, I used the same settings to run Skylines 1 on my Mac but Windows version. Seems to work better than the Mac version.

**Comment by TylerAustin7** [comment]
I am having the same issue while I am using MacBook Air m2
