### ISSUE TITLE
Can't save game?

### ISSUE THREAD

**Issue by FezVrasta** [manolz1/cities2-gptk-fix#2]
Whenever I try to save the game I get an error, I wasn't able to copy it as it resulted in random chinese characters for some reason...

```
捯瑡潩剮㑎汬浶ㄱ慲彷獯牴慥䕭䭐华ㅟ䐰䱉捯瑡潩䕮乒㈱䝟佌䅂彌也ㅟ㘱獁坭楲整䍲湯整瑸E彟乚㈱䝟佌䅂彌也ㅟ㐱䑍楆汥偤楲瑮牥瀸楲瑮湉䥴䕪癅㑎汬浶匹牴湩剧晥呅扟开婟ㅎ弲䱇䉏䱁彟彎ㄱ䴴䙄敩摬牐湩整ㅲ瀳楲瑮敍慴慤慴久水癬㥭瑓楲杮敒䕦䭐华弱䴸瑥摡瑡䕡b彟乚㈱䝟佌䅂彌也ㅟ㐱䑍楆汥偤楲瑮牥瀹楲瑮潂汯久水癬㥭瑓楲杮敒䕦乢ㅓ㡟灏楴湯污扉䕅开婟㉌眲楲整敍慴慤慴獁灏牥湡剤㑎汬浶ㄱ慲彷獯牴慥䕭䭐华㡟敍慴慤慴剅ㅎ弲䱇䉏䱁彟彎ㄱ䄶浳牗瑩牥潃瑮硥䕴开婟ㅌ朴瑥楌歮条乥浡乥水癬ㅭ䜱潬慢噬污敵㈱楌歮条呥灹獥E彟䱚㜱牣慥整汓瑯牔捡敫偲之水癬㕭慖畬䕥开婟䭎水癬ㅭ䐲湥敳慍䉰獡䥥华㡟敄獮䵥灡偉之当䘸湵瑣潩䕮华㥟慍噰捥潴䥲䭐华㕟慖畬䕥华㍴彟㘱敶瑣牯橉华弹愹汬捯瑡牯橉䕅䕅华弱卉弸乪当㈱敄獮䵥灡湉潦卉弸䕶久当搶瑥楡ㅬ䐲湥敳慍偰楡䥲㡓機䕅䕅华彁义㥓㑟慰物卉弸䑓䕟久䉓䥟䱓䕟䕅䕅久䕓䥟㑓癟䕅华彈卉弴体䕟䕅卅弴体卟彐兓䕟㔱潌歯灵畂正瑥潆䥲㑓䕟扅䭒彔偒卋彑开婟㑎汬浶䐸湥敳慍䥰䭐华㡟畆据楴湯久当䴹灡敖瑣牯偉之当嘵污敵久瑓弳ㅟ瘶捥潴䥲乪㡓㥟污潬慣潴䥲䕪䕅久こ䥟㝓機华ㅟ䐲湥敳慍䥰普䥯㝓癟䕅华㙟敤慴汩㈱敄獮䵥灡慐物卉強䕪䕅久㥓䥟华弸瀴楡䥲㝓卟彃䕅华彁卉彋䕅䕅䕅华彄卉弳䕶久䝓䥟㍓卟彎䕅䑅䔲v彟乚瑓弳ㅟ瘶捥潴䥲华㑟慰物偉之水癬㕭慖畬䕥华弰橉华㥟污潬慣潴䥲䕪䕅䕅久㙓䥟㥓䕟䕅㉄㙂ㅶ〵㘰癅开婟㑎汬浶ㄲ潦浲瑡整彤慲彷獯牴慥䑭䔲v彟乚水癬ㅭ匱潬呴慲正牥㉄癅开婟㑎汬浶匹牴湩䵧灡橉华ㅟ䴵污潬䅣汬捯瑡牯䕅㉄癅开婟㑎汬浶㈱敄獮䵥灡慂敳义当䐸湥敳慍䥰䭐华㕟慖畬䕥乪当㈱敄獮䵥灡湉潦卉弴䕶久当搶瑥楡ㅬ䐲湥敳慍偰楡䥲㑓機䕅䕅㑓機㙓卟弹ㅅ琱祲敟灭慬散䩉䭒䕪䕅华㍴彟㐱慰物义当㘱敄獮䵥灡瑉牥瑡牯卉弴卪弶㥓䱟ぢ䕅扅䕅䭒㑓䑟佰彔开婟㑎汬浶㈱敄獮䵥灡慂敳义当䐸湥敳慍䥰䭐华㕟慖畬䕥乪当㈱敄獮䵥灡湉潦卉弴䕶久当搶瑥楡ㅬ䐲湥敳慍偰楡䥲㑓機䕅䕅㑓機㙓卟弹ㅅ洸癯䙥潲佭摬畂正瑥䕳卐弹䍓_彟乚水癬㉭匳慭汬敖瑣牯敔灭慬整慂敳义瑓弳ㅟ瀴楡䥲䭐华㍟獕䕥䕪䱅ㅢ䕅瀹獵彨慢正卅弶开婟华㍴彟ㄱ弱楟瑮潲潳瑲义当㜱䍟慬獳捩汁偧汯捩䕹婒㉌瀴敲楤瑣慖畬啥敳楌瑳牏敤偲之水癬㕭慖畬䕥剪之㉓㥟慍噰捥潴䥲㕓機华弲䐸湥敳慍䥰㕓機华弲㈱敄獮䵥灡湉潦卉張䕶久㉓㙟敤慴汩㈱敄獮䵥灡慐物卉張䕪䕅久当瘶捥潴䥲华㑟慰物卉張䕪久当愹汬捯瑡牯卉彇䕅䕅䕅㍅弤倱华彆偉之㉓㍟獕䕥䕪䕅癅ㅔ卟录ご也当㔱瑩牥瑡牯瑟慲瑩䥳啓䕟㔱楤晦牥湥散瑟灹䕥开婟䱚㐲牰摥捩噴污敵獕䱥獩佴摲牥䭐㑎汬浶嘵污敵橅䭒华㥟慍噰捥潴䥲㉓機华㡟敄獮䵥灡卉弲乪当㈱敄獮䵥灡湉潦卉弲䕶久当搶瑥楡ㅬ䐲湥敳慍偰楡䥲㉓機䕅䕅华㍴彟㘱敶瑣牯义䉓㑟慰物卉弲䕪久䉓㥟污潬慣潴䥲䕓䕟䕅䕅䕅䭎␳ㅟ汣剅之䑓䥟䭐华㍟獕䕥䕪卅归开婟华㍴彟ㄱ弹獟牯㕴睟慲彰潰楬祣义当㜱䍟慬獳捩汁偧汯捩䕹婒㉌瀴敲楤瑣慖畬啥敳楌瑳牏敤偲之水癬㕭慖畬䕥剪之㉓㥟慍噰捥潴䥲㕓機华弲䐸湥敳慍䥰㕓機华弲㈱敄獮䵥灡湉潦卉張䕶久㉓㙟敤慴汩㈱敄獮䵥灡慐物卉張䕪䕅久当瘶捥潴䥲华㑟慰物卉張䕪久当愹汬捯瑡牯卉彇䕅䕅䕅㍅弤倱华彆偉之㉓㍟獕䕥䕪䕅橅ㅔ卟录啓卟录啓呟弰开婟华㍴彟㜱彟潳瑲䤳华ㅟ強汃獡楳䅣杬潐楬祣剅䱚㐲牰摥捩噴污敵獕䱥獩佴摲牥䭐㑎汬浶嘵污敵橅䭒华弲䴹灡敖瑣牯卉張乪㉓㡟敄獮䵥灡卉張乪㉓ㅟ䐲湥敳慍䥰普䥯㕓癟䕅华弲搶瑥楡ㅬ䐲湥敳慍偰楡䥲㕓機䕅䕅华㙟敶瑣牯义当瀴楡䥲㕓機䕅华㥟污潬慣潴䥲䝓䕟䕅䕅䕅␳ㅟ乐䙓䥟䭐华弲唳敳橅䕅䕅呪弱啓卟录ご_彟乚瑓弳ㅟ㜲彟湩敳瑲潩彮潳瑲楟据浯汰瑥䥥婒㉌瀴敲楤瑣慖畬啥敳楌瑳牏敤偲之水癬㕭慖畬䕥剪之ㅓ㥟慍噰捥潴䥲㑓機华弱䐸湥敳慍䥰㑓機华弱㈱敄獮䵥灡湉潦卉弴䕶久ㅓ㙟敤慴汩㈱敄獮䵥灡慐物卉弴䕪䕅久当瘶捥潴䥲华㑟慰物卉弴䕪久当愹汬捯瑡牯卉彆䕅䕅䕅㍅弤倱华彅偉之ㅓ㍟獕䕥䕪䕅扅ご卟彔彔开婟华㍴彟㜱彟潳瑲䤴华ㅟ強汃獡楳䅣杬潐楬祣剅䱚㐲牰摥捩噴污敵獕䱥獩佴摲牥䭐㑎汬浶嘵污敵橅䭒华弲䴹灡敖瑣牯卉張乪㉓㡟敄獮䵥灡卉張乪㉓ㅟ䐲湥敳慍䥰普䥯㕓癟䕅华弲搶瑥楡ㅬ䐲湥敳慍偰楡䥲㕓機䕅䕅华㙟敶瑣牯义当瀴楡䥲㕓機䕅华㥟污潬慣潴䥲䝓䕟䕅䕅䕅␳ㅟ乐䙓䥟䭐华弲唳敳橅䕅䕅呪弱啓卟录啓呟弰开婟华㍴彟ㄱ弱獟晩彴潤湷义当㜱䍟慬獳捩汁偧汯捩䕹婒㉌瀴敲楤瑣慖畬啥敳楌瑳牏敤偲之水癬㕭慖畬䕥剪之㉓㥟慍噰捥潴䥲㕓機华弲䐸湥敳慍䥰㕓機华弲㈱敄獮䵥灡湉潦卉張䕶久㉓㙟敤慴汩㈱敄獮䵥灡慐物卉張䕪䕅久当瘶捥潴䥲华㑟慰物卉張䕪久当愹汬捯瑡牯卉彇䕅䕅䕅㍅弤倱华彆偉之㉓㍟獕䕥䕪䕅癅ㅔ佟ご也当㔱瑩牥瑡牯瑟慲瑩䥳啓䕟㔱楤晦牥湥散瑟灹䕥啓_彟乚水癬㡭敄獮䵥灡偉之当䘸湵瑣潩䕮华㥟慍噰捥潴䥲䭐华㕟慖畬䕥华㍴彟㘱敶瑣牯橉华弸愹汬捯瑡牯橉䕅䕅华弰卉強乪当㈱敄獮䵥灡湉潦卉強䕶久当搶瑥楡ㅬ䐲湥敳慍偰楡䥲㝓機䕅䕅华弹义㡓㑟慰物卉強䍓䕟久䅓䥟䭓䕟䕅䕅久䑓䥟㍓癟䕅华彇卉弳乓䕟䕅朴潲䕷j彟乚水癬㡭敄獮䵥灡偉之当嘵污敵橅华ㅟ䐲湥敳慍䥰普䥯㍓癟䕅华㙟敤慴汩㈱敄獮䵥灡慐物卉弳䕪䕅椴楮䕴j彟乚瑓弳ㅟ瘶捥潴䥲华㑟慰物偉之水癬㕭慖畬䕥华弰橉华㥟污潬慣潴䥲䕪䕅䕅久㙓䥟㥓䕟䕅瀹獵彨慢正㙂ㅶ〵㘰佅㥓_彟乚瑓弳ㅟ瘶捥潴䥲华㑟慰物偉之水癬㕭慖畬䕥华弰橉华㥟污潬慣潴䥲䕪䕅䕅久㙓䥟㥓䕟䕅ㄲ彟異桳扟捡彫汳睯灟瑡䥨㥓䕟癅呏_彟乚㈱䝟佌䅂彌也ㅟ㈱祔数牐湩楴杮㘱湩潣灲牯瑡呥灹獥癅开婟㑎汬浶䐸湥敳慍䥰乐当〱瑓畲瑣祔数橅华ㅟ䐲湥敳慍䥰普䥯㉓癟䕅华㙟敤慴汩㈱敄獮䵥灡慐物卉弲䕪䕅朴潲䕷j彟
```

![CleanShot 2023-12-31 at 1  59 14@2x](https://github.com/manolz1/cities2-gptk-fix/assets/5382443/fcd37ea3-bf1d-4359-871c-23353c0701f3)

**Comment by manolz1** [comment]
@FezVrasta this is a game bug, are you on the latest version of the game? Looking at the patch notes, there seems to have been some fixes around save games. I'd try create a brand new map and try and save, if it works then your current map is corrupted somehow.

Also try a steam integrity check to make sure there's no issues with your game files

**Comment by FezVrasta** [comment]
It's a fresh installation of the game on a new map. I though it could be related to wine because of that

**Comment by manolz1** [comment]
@FezVrasta Unity has a system called "addressables" to find/read assets, and from the error it seems it's either failed to read/write an asset or tried to read/write an asset that doesn't exist.

Is your game located on an external drive by any chance? 

Also have you tried downloading a save file online somewhere that someone has uploaded, loading it, and then try saving it?

**Comment by manolz1** [comment]
@FezVrasta also double check your paradox launcher settings and try toggle the language back and forth to your desired language, someone else had some issues with the game defaulting to Chinese. I wonder if its trying to save the game with Chinese characters and causing issues

https://steamcommunity.com/app/949230/discussions/0/3878221560446876956/

**Comment by manolz1** [comment]
Closing issue
